- README.md
Added documentation on how to initialize the Cloudant library sychronously
> Added documentation for synchronous init of library

- cloudant.js
If the password contained an @ or ?, then the URL would not have been formed properly. Fixed by using EncodeURLComponent around such data.
> Encoded URL components correctly. Fixes issue #32

- README.md
- cloudant.js
This addresses Issue #34 but is branched from the PR about Issue #6, which added other functions for authorisation.
> Add "cors" function to configure CORS

- example/crud.js
Small typo
Fernando <fdov88@gmail.com>
> Fixed incorrect log for deleteDatabase function

- example/README.md
I was trying to get this going, and stumbled across this file in @haengematte's version of this example. (https://github.com/cloudant/haengematte/tree/master/nodejs)
> Create README.md for crud example

- lib/reconfigure.js
- tests/reconfigure.js
> Update account matching regex to allow dashes in account name

- cloudant.js
- package.json
- plugins/promises.js
- tests/plugin.js
Small fixes to the 'promises' plugin, as per issue #151 and issue #152
> Promisesissues

- package.json
- plugins/retry.js
- tests/plugin.js
Allow the retry plugin to be called without a callback.
> Retry plugin without callback

- package.json
Makes sensible choices about encoding parameters when making search calls.
> 1.6.2 - fix issue #163

- cloudant.js
- lib/reconfigure.js
- tests/reconfigure.js
Parse URLS to make sure they are URLs before allowing the initialisation to continue.
> better error checking in the reconfigure function

- .travis.yml
- package.json
- tests/api.js
- tests/plugin.js
- tests/readme-examples.js
Also, include `nsp check` in test suite & fix some tests.
> Bump cloudant-nano dep

- plugins/retry.js
> Remove old comment from retry plugin

- .eslintignore
- .eslintrc.json
- cloudant.js
- example/crud.js
- lib/reconfigure.js
- package.json
- plugins/cookieauth.js
- plugins/default.js
- plugins/promises.js
- plugins/retry.js
- tests/api.js
- tests/nock.js
- tests/plugin.js
- tests/readme-examples.js
- tests/reconfigure.js
> Add eslint

- Jenkinsfile
- package.json
- tests/api.js
- tests/plugin.js
- tests/readme-examples.js
Some quick and dirty fixes to get the jenkins tests passing.
I hope to pretty this up a bit with the forthcoming multiple plugin & IAM auth work.
- Use a different test database name for each `describe` block in `api.js`.
- Add `@before` & `@after` hooks in `plugin.js` to correctly setup test environment.
- Skip mock-only tests.
- Apply `eslint --fix`.
> Fix jenkins tests

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- DCO1.1.txt
Update `CONTRIBUTING.md` with DCO instructions.
> Update CONTRIBUTING.md with DCO instructions

- CHANGES.md
- package.json
Update request to avoid a vulnerability in tunnel-agent < 0.6.0
Changed package.json to reflect the dependency change.
How the change was implemented and reasoning behind it, e.g. Added create_index API to allow
the creation of text and json indexes.
N/A
connected to https://github.com/cloudant/nodejs-cloudant/issues/202
> package: use request@^2.81.0

- Jenkinsfile
- package.json
- Scope package under `@cloudant` NPM org.
- Add Jenkins publish stage.
> Add jenkins publish stage

- lib/client.js
- package.json
- plugins/base.js
- plugins/retry.js
- plugins/retry429.js
- plugins/retry5xx.js
- plugins/retryerror.js
- test/fixtures/testplugins.js
- test/plugins/retry429.js
- test/plugins/retry5xx.js
- test/plugins/retryerror.js
Implement following plugins:
- `retry429` (aka `retry`)
- `retry5xx`
- `retryerror`
> Add retry plugins

- lib/client.js
- lib/eventpipe.js
- test/eventpipe.js
Add option to allow data to be piped from source to target.
Includes additional unit test.
> Add pipeData option to EventPipe

- lib/clientutils.js
Add some better comments to the `processState` function.
> Add comments to processState logic

- lib/client.js
- package.json
- plugins/base.js
- plugins/cookieauth.js
- test/plugins/cookieauth.js
> Add cookieauth plugin

- cloudant.js
- Change 'invalid url' message to error object
- Remove dupe `set_cors` func.
- Update documentation links.
> Tidy cloudant js

- cloudant.js
- lib/client.js
- test/client.js
- test/fixtures/testplugins.js
- test/legacy/api.js
- test/legacy/plugin.js
- test/legacy/readme-examples.js
Use the new Cloudant client in `cloudant.js`.
Pass the Cloudant client instance through to the underlying nano object.
Includes additional/updated unit tests.
> Use cloudant client

- CHANGES.md
- package.json
- test/api.js
- test/plugin.js
- test/readme-examples.js
I have fixed the test suite (`npm test`)
- Upgrading debug to 3.1.0 fixes the vulnerability error. 
- Adding `{silent: true}` to dotenv to prevent `.env` warnings.
Run `npm test`
issue: https://github.com/cloudant/nodejs-cloudant/issues/223
> fixup tests

- Jenkinsfile
- lib/client.js
- test/client.js
- test/legacy/readme-examples.js
- test/plugins/iamauth.js
Enable `cookieauth` plugin if no plugins are specified at client construction time.
Set plugin array to `['cookieauth']` by default.
Includes unit tests.
> Enable cookie auth

- CHANGES.md
- package.json
> Use latest debug@3.x.x

- CHANGES.md
- package.json
> Use cloudant-nano@6.6.0

- CHANGES.md
- package.json
Prepare 1.9.0 release.
Fixes #229.
> Prepare 1.9.0 release

- CHANGES.md
- package.json
> Use cloudant-nano@6.7.0

- CHANGES.md
- package.json
Prepare version 1.10.0 release.
> Prepare version 1.10.0 release

- cloudant.js
- lib/client.js
- lib/clientutils.js
- lib/eventpipe.js
- lib/eventrelay.js
- plugins/base.js
- plugins/cookieauth.js
- test/client.js
- test/clientutils.js
- test/eventrelay.js
- test/legacy/plugin.js
- test/plugins/cookieauth.js
Refactor `EventPipe` and `CloudantClient` using ES2015 style classes.
> Use ES2015 style classes

- CHANGES.md
- README.md
- cloudant.js
This reverts commit efca9e38fc16d8c2a5cbb4299d5447edf1a0683d.
I will make these changes following the merge of #243.
> Revert "Updated deprecated links to the latest Bluemix Cloudant documentation links."

- README.md
Document debuggers in `README.md`.
Fixes #249.
> Document debuggers in README.md

- plugins/cookieauth.js
- plugins/iamauth.js
- test/plugins/cookieauth.js
- test/plugins/iamauth.js
Wait until first request is made before attempting to exchange auth tokens.
Remove session exchange logic from plugin constructors.
Updated unit tests.
> Disable auth exchange on build

- api-migration.md
Include piping note in `api-migration.md`.
> Include piping note in api-migration.md

- README.md
Improve client initialization documentation.
Fixes #168.
> Improve client initialization documentation

- CHANGES.md
- cloudant.js
- test/cloudant.js
Fix `get_security`/`set_security` asymmetry.
Updates unit tests.
Fixes #139.
> 139 fix security asymmetry

- README.md
Document IAM plugin.
Fixes #256.
> Document IAM plugin

- CHANGES.md
- README.md
- api-migration.md
- cloudant.js
- lib/client.js
- lib/clientutils.js
- plugins/base.js
- plugins/cookieauth.js
- plugins/iamauth.js
- plugins/retry429.js
- plugins/retry5xx.js
- plugins/retryerror.js
- test/client.js
- test/clientutils.js
- test/fixtures/testplugins.js
- test/legacy/api.js
- test/legacy/plugin.js
- test/legacy/readme-examples.js
- test/plugins/cookieauth.js
- test/plugins/iamauth.js
- test/plugins/retry429.js
- test/plugins/retry5xx.js
- test/plugins/retryerror.js
Scope plugin configuration, for example:
```js
var cloudant = new Cloudant({ url: myUrl, iamApiKey: 'xxxxxxxxxx', plugin: 'iamauth' });
```
_becomes..._
```js
var cloudant = new Cloudant({ url: myUrl, plugin: { iamauth: { iamApiKey: 'xxxxxxxxxx' } } });
```
Also, removes support for legacy configuration flags.
Gather configuration on client construction, applying defaults as required. Don't allow configuration changes at request time. Don't pass plugin configuration around in the `state`.
Updates affected unit tests.
Fixes #255.
> Scope plugin config

- README.md
- plugins/iamauth.js
- test/plugins/iamauth.js
Update default IAM token service URL.
`https://iam.bluemix.net/oidc/token` ➤ `https://iam.bluemix.net/identity/token`
Updated affected unit tests.
> Update default IAM token service URL

- CHANGES.md
- api-migration.md
- lib/client.js
- lib/error.js
- test/cloudant.js
- test/stream.js
Some stuff raised during testing...
> Testing fixes

- soak_tests/README.md
- soak_tests/animaldb_bulk_docs.json
- soak_tests/doc.json
- soak_tests/soak.js
> Add soak tests

- CHANGES.md
- README.md
- example/crud.js
- example/package.json
- package.json
- test/legacy/readme-examples.js
Update `require` references to scoped package `@cloudant/cloudant`.
> Update require references to scoped package

- README.md
Add enforcing TLS 1.2 note to `README.md`.
- Fixes #271.
> Add enforcing TLS 1.2 note

- CHANGES.md
- cloudant.js
- package.json
> Use nano==6.4.3 dependancy

- CHANGES.md
- types/index.d.ts
- types/tests.ts
Add missing `maxAttempt` to declaration file and update TS tests.
Fixes #290.
> Update TS for maxAttempt configuration

- lib/clientutils.js
Refactor function `processState`. This PR _only_ restructures existing code. There is no change to external behaviour.
> Refactor process state logic

- CHANGES.md
- README.md
- types/index.d.ts
- types/tests.ts
Update TypeScript for client initialization callback.
Fixes #291.
> 291 fix ts cloudant init

- package-lock.json
- package.json
- test/legacy/plugin.js
- test/plugins/cookieauth.js
- test/plugins/retry.js
Fix `npm audit`.
```
$ npm audit
=== npm audit security report ===                        
[+] no known vulnerabilities found
Packages audited: 888 (639 dev, 18 optional)
```
Bump some dependancies & make a couple of minor fixes to the unit tests.
> Fix npm audit

- package.json
- test/passthroughduplex.js
Use readable stream in capture pipe event test.
Fixes #310.
> Use readable stream in capture pipe event test

- CHANGES.md
- package.json
> Prepare 2.3.0 release

- Jenkinsfile
Added gitTagAndPublish step to Jenkinsfile.
Added the common gitTagAndPublish step.
Used common `VersionHelper` and removed duplicate version parsing.
No change
No change
- N/A build or packaging only changes
No change
> Added gitTagAndPublish step to Jenkinsfile

- CONTRIBUTING.md
- soak_tests/soak.js
- test/client.js
- test/clientutils.js
- test/cloudant.js
- test/fixtures/testplugins.js
- test/issues/292.js
- test/legacy/api.js
- test/legacy/plugin.js
- test/legacy/readme-examples.js
- test/plugins/cookieauth.js
- test/plugins/iamauth.js
- test/plugins/retry.js
- test/stream.js
Facilitate other modes of integration testing by:
* allowing custom server urls in tests
* tagging tests that can use a real database
Allowed for custom URL for test server by:
* Set `SERVER` value from `SERVER_URL`
* Instantiate test clients using `url: SERVER, username: ME` instead of `account: ME` where applicable.
Added `#db` tag to tests that can use a real DB to facilitate mocha's `grep` filtering.
- "No change"
- "No change"
- Modified existing tests because it was not possible previously to test with any URL and it was not possible to run just (a selection of) the tests that use a real database.
- "No change"
> Custom url & test tagging

- CHANGES.md
- package.json
Remove unnecessary `@types/nano dependancy`.
Fixes #355.
No change.
No change.
No change.
No change.
> Remove unnecessary @types/nano dependancy

- CHANGES.md
- README.md
- plugins/iamauth.js
- test/plugins/iamauth.js
Update the default IAM token server URL.
No change.
No change.
No change.
No change.
> Update the default IAM token server URL

- CHANGES.md
- package-lock.json
- package.json
- types/index.d.ts
- types/tests.ts
Add `vcapServiceName` configuration option to TS declarations.
Also, use `nano.DocumentSearchParams` instead of `cloudant.SearchParams` and remove unused interface.
No change.
No change.
Includes additional TS test.
No change.
> 365 fix vcap ts def

- package-lock.json
- test/legacy/plugin.js
> Remove erroneous `it.only`.

- CHANGES.md
- package.json
- [NEW] Added partitioned database support.
> Prepare version 4.1.0 release.

- package-lock.json
Run `npm audit fix`.
N/A
No change.
No change.
N/A
No change.
> Run `npm audit fix`.

- CHANGES.md
- README.md
- lib/client.js
- plugins/iamauth.js
- test/plugins/iamauth.js
- test/readmeexamples.js
Retry bad IAM token requests.
Fixes #385.
Catch `5xx` & `429` status codes and invoke retry mechanism (by _not_ setting `shouldApplyIAMAuth` to `false`).
No change.
No change.
Updated unit tests.
No change.
> Retry bad IAM token requests.

- CHANGES.md
- lib/client.js
Include all built-in plugin modules in webpack bundle.
Fixes #389.
No change.
No change.
No change.
No change.
> Include all built-in plugin modules in webpack bundle.

- CHANGES.md
- README.md
- plugins/iamauth.js
- test/plugins/iamauth.js
Error when user cannot be authenticated using IAM.
Includes additional/updated unit tests.
No change.
> Error when user cannot be authenticated using IAM.

- lib/tokens/CookieTokenManager.js
- lib/tokens/TokenManager.js
- package-lock.json
- package.json
- test/tokens/TokenManager.js
Add `CookieTokenManager` class for managing cookie session renewals.
The cookie renewal logic has been centralised into a token manager class. Once implemented fully, the cookie authentication plugin will make `.renew()` requests against the token manager class. The token manager class is designed to avoid unnecessary renewals and operate without needing the `lockfile` dependancy (to be removed in a later PR).
No change.
No change.
Includes additional unit tests. Existing cookie authentication tests will be used to test `CookieTokenManager` logic.
No change.
> Cookie token manager

- lib/client.js
- lib/tokens/TokenManager.js
- plugins/cookieauth.js
- test/client.js
- test/cloudant.js
- test/issues/292.js
- test/legacy/api.js
- test/legacy/plugin.js
- test/legacy/readme-examples.js
- test/plugins/cookieauth.js
- test/plugins/retry.js
- test/readmeexamples.js
Use the new `CookieTokenManager` (see #397) in the `cookieauth` plugin.
Remove cookie renewal logic from plugin code and use `CookieTokenManager` instead.
No change.
No change.
Update existing tests as follows:
- Don't include the `cookieauth` plugin by default in test clients.
- Pass the server URL to the Cloudant client (where required).
- Disable auto renewing of cookie session in tests (for easier mocking).
No change.
> Use cookie token manager

- lib/tokens/IamTokenManager.js
- lib/tokens/TokenManager.js
- plugins/iamauth.js
- test/plugins/iamauth.js
Add `IAMTokenManager` class for managing cookie session renewals.
Use token manager approach as per #397.
No change.
No change.
Covered by existing unit tests.
No change.
> Iam token manager

- README.md
Updated README.md to use code highlight.
Updated README.md
No change
No change
N/A build or packaging only changes
No change
> docs: add code highlighting

- CHANGES.md
- Jenkinsfile
- README.md
- lib/client.js
- lib/tokens/CookieTokenManager.js
- lib/tokens/IamTokenManager.js
- lib/tokens/TokenManager.js
- package-lock.json
- package.json
- plugins/cookieauth.js
- plugins/iamauth.js
- test/client.js
- test/cloudant.js
- test/issues/292.js
- test/legacy/api.js
- test/legacy/plugin.js
- test/legacy/readme-examples.js
- test/plugins/cookieauth.js
- test/plugins/iamauth.js
- test/plugins/retry.js
- test/readmeexamples.js
- test/tokens/TokenManager.js
Add new Token Manager for managing authentication tokens.
The manager blocks concurrent token requests. It also preemptively refreshes a token before it expires (dictated by `Max-Age`).
The Token Manger is used for both Cookie and IAM authentication.
- Add new `TokenManager` class (including`CookieTokenManager` and `IAMTokenManager` subclasses).
- Call the manager when requesting an authentication token.
None.
None.
Adds new logging namespaces for `TokenManager` type classes.
> Feature Branch: Add Token Manager

- test/partitioned_databases.js
This reverts commit 062f48b92e89ce4ab40971eac7bff865454a420a.
> Revert "Run partitioned_databases.js tests only against Cloudant databases."

- README.md
- package-lock.json
- package.json
Under some circumstances there is a memory leak when the Cloudant client is instantiated more than one times during an application lifetime.
``` javascript
var Cloudant = require('./cloudant');
const http = require('http');
const server = http.createServer((req, res) => {
var cloudantBasic = Cloudant({
//account setting
plugins: 'cookieauth'
});
async function getDbList() {
return cloudantBasic.db.list();
}
getDbList().then(result => {
res.statusCode = 200;
res.end(JSON.stringify(result) + '\n');
console.log('####test success');
}).catch(err => {
res.statusCode = 401;
res.end(err.error + '\n');
console.log('####test failed', err);
});
});
server.listen(3000);
console.log('Server listening to port 3000. Press Ctrl+C to stop it.');
```
In this case when the server receives a request it will …
> Memory leak readme

- CHANGES.md
- package-lock.json
- package.json
- Upgrade `nano` version to 8.2.2
- Upgrade `@types/request` to '2.48.4'
Fixes #428 
Update dependencies in `package.json`
"No change"
N/A build or packaging only changes.  Existing tests are passing.
> Upgrade nano and types/request dependencies

- CHANGES.md
- package-lock.json
- package.json
Proposed 4.3.0 release:
- [FIXED] Stopped constant token auto renewal in the absence of a cookie
header Max-Age.
- [UPGRADED] Upgrade package: @types/request@^2.48.4.
- [UPGRADED] Upgrade package: nano@~8.2.2.
> Prepare 4.3.0 release

- MIGRATION.md
Update migration guide for _replicator DB functions.
Fixes #433
Updated function names and links.
- "No change"
- "No change"
Docs change
- "No change"
> Update migration guide for _replicator DB

- CHANGES.md
- package-lock.json
- package.json
- [NEW] Add migration guide to new SDK.
- [FIXED] Update README to prefer url to account.
> Prepare 4.3.1 release

- package-lock.json
- package.json
Bump package to 4.3.2-SNAPSHOT
> Updated version to 4.3.2-SNAPSHOT

- README.md
Update links to IBM Cloud&trade; documentation site to new paths in README. Link to `api#ping` removed as it is not on API docs anymore.
> Update and/or fix IBM Cloud docs links

- .travis.yml
- Jenkinsfile
- [x ] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](../blob/master/DCO1.1.txt)
- [x ] Added tests for code changes _or_ test/build only changes
- [x ] Updated the change log file (`CHANGES.md`|`CHANGELOG.md`) _or_ test/build only changes
- [x ] Completed the PR template below:
Set Node.js test versions to `12`, `14` and `16`
Fixes #467 
Update `Jenkinsfile` and `.travis.yml` to use active LTS `16` instead of `17` by changing `node` for `16`.
- "No change"
- "No change"
Changed Node.js test versions.
- "No change"
> Update test versions
