cloudant/nodejs-cloudant

- README.md
- cloudant.js
Fixes #6 
The current release uses the deprecated APIs for assigning permissions to users. I've kept these calls the same, but added a deprecation warning and added two new function calls:
* cloudant.view_security(db, callback)
* cloudant.set_security(db, security, callback)
I've followed the same verbs as the other API calls and haven't attempted to hide what the API is doing e.g. I haven't tried to abstract e.g. cloudant.set_role(db, user, roles), for instance.
The functions are wangled into Nano using the same fix_request as the other Cloudant-specific functions.
> Added support for _security Cloudant endpoints

- README.md
Typo fix so that the Cloudant call is using the variable instead of the string.
> Fix complete example to use the 'me' variable instead of the string 'me'

- README.md
The signature and link were both incorrect for the `db.insert` function in the Table of Contents
> Fixing db.insert signature in ToC

- README.md
Syntax highlight was incorrect due to missing quotation mark.
> Add missing single quotes from README.md

- cloudant.js
I noticed in our cloudant.js code we were doing:
```
function x(callback) {
nano.request({something:true}, callback);
}
```
That's fine unless you want to stream the output 
```
cloudant.x().pipe(res)
```
So I needed to modify our code to ensure that we always return the nano request object.
> ensure that the nano.request object is returned to allow streaming

- lib/reconfigure.js
- tests/reconfigure.js
Fixes #129.
Tests:
`npm test`
I noticed some of the other tests do fail, though.
> Removes a trailing `/` from a manually specified URL.

- cloudant.js
Uses the built-in http/https agent with `keepAlive: true` following the discussion in issue #145.
> switched keep-alive on by default - fixes issue #145

- README.md
- plugins/retry.js
- tests/plugin.js
Modifies the retry plugin to make it return a stream.PassThrough object which is fed content from a successful (non-429) request. This allows the pipe operator to be used.
> make retry plugin return a stream. Fixes issue #154

- README.md
- cloudant.js
- plugins/cookieauth.js
- tests/plugin.js
Adds new `cookieauth` plugin that transparently
- exchanges Cloudant credentials for a cookie
- sends the cookie with each request from that point on
- pings Cloudant hourly to refresh the cookie
> New cookieauth plugin re issue #120

- README.md
- lib/reconfigure.js
- tests/reconfigure.js
Initialize Cloudant by parsing a VCAP_SERVICES environment variable
allowing easy binding of a service instance to a Cloud Foundry
application.
Example usage:
```
var cloudant = Cloudant({vcapServices: JSON.parse(process.env.VCAP_SERVICES)});
```
Fixes #173.
> Add option to initialize Cloudant using VCAP

- .npmignore
This pull request adds a `.npmignore` file. The idea is to not publish the `example` or `tests` folder into npm.
> Create .npmignore and ignore examples and tests

- lib/eventpipe.js
- test/eventpipe.js
Add `EventPipe` object to forward events from a source emitter to a target emitter.
Store fired events in an array until `.resume()` is called. Then replay captured events (and any new events received) on the target emitter.
> Add event pipe

- lib/client.js
- lib/clientutils.js
- plugins/base.js
- test/client.js
- test/clientutils.js
- test/fixtures/testplugins.js
Add new `CloudantClient` that supports multiple request interceptor plugins.
Run intercepter hooks on `request`, `error` and `response` events.
- Creating a `CloudantClient`:
```js
var client = new CloudantClient({ maxAttempt: 10, plugins: [ 'cookieauth', 'retry5xx' ] });
client.request({ url: 'http://localhost:5984/mydb' })
.on('response', function(resp) {
console.log(resp.statusCode);
});
```
- A `CloudantClient` plugin:
```js
function retry5xx(client, opts) {
retry5xx.super_.apply(this, arguments);
}
retry5xx.super_ = BasePlugin;
retry5xx.prototype = Object.create(BasePlugin.prototype);
retry5xx.prototype.onResponse = function(state, response, callback) {
if (response.statusCode >= 500) {
state.retry = true; // retry request
// set delay before next retry
if (state.attempt === 1) { …
```
> Add Cloudant client

- lib/client.js
- lib/clientutils.js
Ensure `processState` is always executed even if plugin hooks fail.
> Always run `processState` after plugin execution

- lib/client.js
- lib/clientutils.js
- test/client.js
- test/clientutils.js
- test/fixtures/testplugins.js
Implement `response.abort()`.
Monkey-patch `request.clientStream.abort` with underlying `response.abort`.
Includes additional unit test.
> Add request abort

- cloudant.js
- lib/client.js
- lib/clientutils.js
- plugins/base.js
- plugins/cookieauth.js
- plugins/retry429.js
- plugins/retry5xx.js
- plugins/retryerror.js
- test/client.js
- test/clientutils.js
- test/fixtures/testplugins.js
Allow client configuration to be changed at request time.
```js
var cfg = { usePromises: true };
cloudantClient.request('http://localhost:5984', cfg).then(function(data) {
...
```
_or_
```js
var cfg =  { retryInitialDelayMsecs: 750 };
cloudantClient.request('http://localhost:5984',cfg, function(err, resp, data) {
...
```
> Override cfg on request

- lib/client.js
- lib/clientutils.js
- test/clientutils.js
- test/fixtures/testplugins.js
Implement `state.stash`. Allows plugin hooks to share data via the request state.
Adapted existing plugin tests.
> Implement state.stash

- cloudant.js
- lib/client.js
- lib/clientutils.js
- lib/eventrelay.js
- plugins/base.js
- plugins/cookieauth.js
- test/client.js
- test/clientutils.js
- test/eventrelay.js
- test/legacy/plugin.js
- test/plugins/cookieauth.js
Support legacy custom plugins.
Includes a couple of additional patches highlighted in testing, namely:
- Remove URL credentials when using cookie authentication.
- Add missing `request.abort()` hook.
> Support legacy custom plugins

- CHANGES.md
- README.md
- cloudant.js
Updated `docs.cloudant.com` links to the latest Bluemix `console.bluemix.net/docs/` documentation.
- Replaced all deprecated links in library with the appropriate Bluemix doc links
No new tests.
fixes #237
> Updated docs.cloudant.com deprecated links

- CHANGES.md
- README.md
_[Rebase of #238 on #243 branch]_
Updated `docs.cloudant.com` links to the latest Bluemix `console.bluemix.net/docs/` documentation.
Replaced all deprecated links in library with the appropriate Bluemix doc links.
No new tests.
Fixes #237.
> 237 update doc links 2

- CHANGES.md
- README.md
- lib/reconfigure.js
- test/legacy/reconfigure.js
Allow custom service name in CloudFoundry `VCAP_SERVICES` env var.
Override default using `config.vcapServiceName`.
Fixes #246.
> Allow custom service name in CloudFoundry VCAP_SERVICES env var

- CHANGES.md
- lib/client.js
- lib/clientutils.js
- lib/eventrelay.js
- lib/passthroughduplex.js
- test/client.js
- test/clientutils.js
- test/eventrelay.js
- test/legacy/plugin.js
- test/passthroughduplex.js
Support payload piping, for example:
```js
fs.createReadStream('keys.json').pipe(cloudant.request({ path: 'my_db/_all_docs', method: 'POST' }).pipe(process.stdout)
```
_Note:_ Additional work is required if these types of request are to be retried since currently the request stream may only be read once. This will be handled in a future PR.
`cloudant.request` now returns a Duplex type which implements both Readable and Writable interfaces allowing both the request and response to be streamed.
See #258.
> Support piping of request payload

- CHANGES.md
- api-migration.md
- lib/client.js
- lib/clientutils.js
- test/clientutils.js
- test/stream.js
This change allows pipes to be defined inside event handlers.
Setup request piping after events have been replayed. This ensures we correctly pipe data where piping has been defined in an event handler.
> Setup request piping after events have been replayed

- CHANGES.md
- package.json
- [NEW] Add TypeScript definitions.
- [NEW] Allow pipes to be defined inside request event handlers.
- [UPGRADED] Using nano==6.4.3 dependancy.
- [NOTE] Update engines in preparation for Node.js 4 “Argon” end-of-life.
> Prepare 2.1.0 release

- CHANGES.md
- cloudant.js
- test/issues/292.js
Support Cloudant query when using promises request plugin.
List all Cloudant NoSQL DB Query indexes:
```js
db.index().then((d) => { console.log(d); });
```
Creating an index:
```js
db.index(definition).then((d) => { console.log(d); })
```
Fixes #292.
> Support Cloudant query when using promises request plugin

- README.md
Add 'Callback Signature' section to README.
Fixes #303.
> Add 'Callback Signature' section to README.

- CHANGES.md
- package.json
- [FIXED] Add missing `maxAttempt` parameter to TypeScript definition.
- [FIXED] Include client initialization callback in TypeScript definition.
- [FIXED] Prevent client executing done callback multiple times.
- [FIXED] Removed test and lint data that bloated npm package size.
- [FIXED] Support Cloudant query when using promises request plugin.
> Prepare 2.2.0 release

- CHANGES.md
- cloudant.js
- lib/client.js
- lib/reconfigure.js
- test/legacy/reconfigure.js
Added support for IAM API key when creating a Cloudant client using `vcapServices`:
```javascript
var VCAP_SERVICES = '{"cloudantNoSQLDB": [{"credentials": {"apikey": "api123key", "username": "bluemix-user"}}]}'
var cloudant = Cloudant({ vcapServices: JSON.parse(VCAP_SERVICES) });
```
- Updated `reconfigure.js` to return a dictionary object with either a) url with legacy creds or b) IAM with url
- If IAM key exists in vcap services, add `IAMPlugin` to client
- Added tests to assert vcap services IAM key in `reconfigure.js`
Added tests in `reconfigure` for asserting IAM key and URL when creating client with single and multiple vcap services.
> Added support for IAM API key when initializing client with VCAP_SERVICES

- CHANGES.md
- lib/client.js
- test/client.js
Removed addition of `statusCode` to response objects.
Update existing unit test to assert object key length.
Fixes #308.
> Removed addition of statusCode to response objects

- README.md
The example for IAM authentication included legacy credentials in the URL. It shouldn't have.
IAM plugin example shouldn't include creds in URL
The example for IAM authentication included legacy credentials in the URL. It shouldn't have. They are removed.
None.
None.
> IAM plugin example shouldn't include creds in URL

- CHANGES.md
- README.md
- lib/reconfigure.js
- test/legacy/reconfigure.js
Properly handle cases when `username`, `password`, and `url` exist during client creation.  This issue was discovered when creating a client against Cloudant Local.
- If `username`, `password`, and `url` exist during client creation, add `username` and `password` to `url`
New test to assert that username and password are added to url in `reconfigure.js`.
fixes #323
> Handle cases when username, password, and url exist during client creation

- .travis.yml
Changed Travis to use `npm install` for compatibility with `package-lock`.
Preemptively fixes the same [style of issue observed in `cloudant-follow`](https://github.com/cloudant-labs/cloudant-follow/issues/78) for greenkeeper branches
Travis uses `npm ci` by default, which does not update the `package-lock` file. Changed the `install` step to explicitly use `npm install`:
```yaml
install: npm install
```
- "No change"
- "No change"
- N/A build or packaging only changes
- "No change"
> Changed to npm install in travis

- Jenkinsfile
- package-lock.json
- package.json
- types/tests.ts
- types/tslint.json
Re-enabled parallel QA stages and changed to `tslint`
Since using `npm install` the `package-lock` versions of `dtslint` seem to be cause linting errors on travis. Reproduce by running:
`npm install`
`npm run dtslint`
Clean linting.
```
The 'strict-export-declare-modifiers' rule threw an error in '/home/travis/build/cloudant/nodejs-cloudant/types/index.d.ts':
TypeError: Cannot read property 'kind' of undefined
at isDeclareGlobalOrExternalModuleDeclaration (/home/travis/build/cloudant/nodejs-cloudant/node_modules/dtslint/bin/rules/strictExportDeclareModifiersRule.js:99:52)
at checkInExternalModule (/home/travis/build/cloudant/nodejs-cloudant/node_modules/dtslint/bin/rules/strictExportDeclareModifiersRule.js:46:14)
at walk (/home/travis/build/cloudant/nodejs-cloudant/node_modules/dtslint/bin …
```
> Lint+test improvements

- test/legacy/api.js
- test/legacy/readme-examples.js
Fixed remaining tests that didn't use a unique db name.
Run tests in parallel.
Tests to pass.
Test failures e.g.
```
QA / Node8x / test.Cloudant Search."before all" hook
Error Message
The database could not be created, the file already exists.
```
#334 re-enabled parallel testing, but no failures happened on the branch before it merged. Once it was merged the master build failed.
Some tests used non-unique DB names, replace these remaining test instances with unique db names.
- "No change"
- "No change"
- Modified existing tests because to correct static db names.
- "No change"
> Refactored remaining tests without unique DB names

- CHANGES.md
- package.json
- [FIXED] Case where `username` and `password` options were not used if a `url` was supplied.
- [FIXED] Case where vcapServices was supplied with a basic-auth url
> Prepare for version 2.4.0 release

- CHANGES.md
- lib/client.js
- test/plugins/iamauth.js
Fix plugin configuration when instantiating a new client using VCAP.
Fixes #340.
Always look at the `plugins` array for user specified plugins.
No change.
No change.
Added additional unit test.
No change.
> Fix plugin configuration when instantiating a new client using VCAP

- CHANGES.md
- cloudant.js
Ensure that Nano always returns a server object.
Add `parseUrl: false` option when instantiating Nano client.
No change.
No change.
Covered in existing test suite.
No change.
> Set `parseURL = false` on underlying Nano instance.

- CHANGES.md
- package.json
- [FIXED] Expose `BasePlugin` type in Cloudant client.
- [FIXED] Set `parseUrl = false` on underlying Nano instance.
- [BREAKING CHANGE] Due to the Nano 7.x upgrade all return types are now a
`Promise` (except for the `...AsStream` functions). _See
[api-migration.md](https://github.com/cloudant/nodejs-cloudant/blob/master/api-migration.md#2x--3x)
for migration details._
- [REMOVED] Remove nodejs-cloudant TypeScript type definitions for
`db.search`. These definitions are now imported directly from Nano.
- [REMOVED] Removed support for the deprecated Cloudant virtual hosts feature.
- [UPGRADED] Using nano==7.1.1 dependency.
> Prepare version 3.0.0 release

- .eslintignore
- CHANGES.md
- package.json
- test/mocha.opts
- test/typescript/cloudant.ts
- types/index.d.ts
Use named import for `request.CoreOptions` type.
Fixes #350.
No change.
No change.
Added new test for importing the typescript types `test/typescript/cloudant.ts`.
No change.
> Use named import for `request.CoreOptions` type

- CHANGES.md
- package.json
- [FIXED] Remove unnecessary `@types/nano` dependancy.
> Prepare version 3.0.2 release

- CHANGES.md
- lib/clientutils.js
- test/client.js
Check valid response before calling `.resume()`.
See #358 - Note this PR does not fix the issue. It propagates the correct error back to the user.
For example:
```js
myDB.attachment.insert(
'doc-123456789'
'pic1',
fs.readFileSync('/tmp/empty_file.txt'), // Content-Length: 0
'plain/txt',
function(err) { console.log(err); }
);
```
_Output:_
```
{ Error: Argument error, options.body.
at setContentLength (/dev/github.com/cloudant/nodejs-cloudant/node_modules/request/request.js:437:28)
at Request.init (/dev/github.com/cloudant/nodejs-cloudant/node_modules/request/request.js:442:5)
...
```
Check for a valid response object before attempting the resume.
No change.
No change.
Adds additional unit tests.
No change.
> Check valid response before resume

- CHANGES.md
- package.json
- [NEW] Added option for client to authenticate with IAM token server.
- [FIXED] Add `vcapServiceName` configuration option to TS declarations.
- [FIXED] Case where `.resume()` was called on an undefined response.
- [FIXED] Updated the default IAM token server URL.
- [BREAKING CHANGE] Nano 7 accepted a callback to the `*AsStream` functions, but
the correct behaviour when using the `request` object from `*AsStream`
functions is to use event handlers. Users of the `*AsStream` functions should
ensure they are using event handlers not callbacks before moving to this
version.
- [UPGRADED] Apache CouchDB Nano to a minimum of version 8 for `*AsStream`
function fixes.
> Prepare version 4.0.0 release

- Jenkinsfile
Removed `sudo` and global install for `npm-cli-login` module during publish step.
Using new Jenkins executor image to run publication step.
Publication without errors
`EACCES` errors are observed during publish (e.g. similar to this for couchbackup):
https://cloudant-sdks-jenkins.swg-devops.com:8443/job/couchbackup/job/master/15/execution/node/103/log/
The `sudo` installation of the `npm-cli-login` package is creating `$HOME/.npm` with `root` as the owner, causing subsequent errors when not running as root.
The package does not need to be installed globally and can therefore be installed without using `sudo` by qualifying the path used for the subsequent commands.
- "No change"
- "No change"
- N/A build or packaging only changes
- "No change"
> Removed sudo from `npm-cli-login` during publish

- README.md
Add Partitioned Databases section to README.md.
> Add partitioned databases section to README.md.

- CHANGES.md
- Jenkinsfile
Running `npm install @cloudant/cloudant` should not install dependencies that are not listed in `package.json`. Starting from `npm@5`, `npm install foo` by default saves `foo` as a dependency, `npm-cli-login` is saved in the `package.json` right before jenkins publishes the package.
you can verify this with `npm view @cloudant/cloudant dependencies`.
I've added `--no-save`, so `npm-cli-login` won't be saved in `dependencies`.
No change
No change
N/A
No change
> Don't add npm-cli-login as a dependency in the published package

- CHANGES.md
- package-lock.json
- package.json
- [FIXED] Remove unnecessary `npm-cli-login` dependency.
> Prepare version 4.1.1 release.

- CHANGES.md
- lib/client.js
- test/client.js
- test/fixtures/testplugin.js
Allow plugins to be loaded from an absolute or relative path
Allow to load plugins based on a relative or absolute path.
Right now plugins can only be loaded if they reside in the `plugins/` directory of the Cloudant NPM module. With this change it's possible to load a plugin from an arbitrary file system location.
Example:
```
let cloudantPluginPath = path.join(process.cwd(), "myPlugin.js");
dbConfig.plugins = [{
[cloudantPluginPath]: {
myParam: 42
}
}];
```
No change
No Change
- Added new tests:
- `plugin support.get plugin path by name`
- `plugin support.get plugin path by relative path`
- `plugin support.get plugin path by absolute path`
No change
> Development (#1)

- CHANGES.md
- package-lock.json
- package.json
- [NEW] Added option to set new IAM API key.
- [FIXED] Allow plugins to be loaded from outside the 'plugins/' directory.
- [FIXED] Retry bad IAM token requests.
> Prepare version 4.2.0 release.

- CHANGES.md
- package-lock.json
- package.json
- [FIXED] Include all built-in plugin modules in webpack bundle.
> Prepare version 4.2.1 release.

- README.md
Removed the `new` keyword in some examples
Removed the `new` keyword in some examples of the use of `Cloudant`.
Using the `new Cloudant` is a syntax error now so it should be removed from the `README.md`
I just updated the `README.md`.
"No change"
- N/A `README.md` only changes
"No change"
> Remove new keyword from README.md

- CHANGES.md
- cloudant.js
- lib/client.js
- lib/clientutils.js
- plugins/base.js
- plugins/cookieauth.js
- test/client.js
- test/plugins/cookieauth.js
Disable cookie authentication if credentials are missing.
If credentials are missing then set a 'disabled' property on the cookie plugin to prevent hooks from being executed.
No change.
No change.
No change.
> Disable cookie authentication if credentials are missing.

- CHANGES.md
- package-lock.json
- package.json
- [FIXED] Stopped disabling the IAM auth plugin after failed IAM
authentications. Subsequent requests will re-request authorization,
potentially failing again if the original authentication failure was not
temporary.
- [FIXED] Ensure IAM API key can be correctly changed.
- [FIXED] Callback with an error when a user cannot be authenticated using IAM.
- [FIXED] Ensure authorization tokens are not unnecessarily requested.
- [IMPROVED] Do not apply cookie authentication by default in the case that no
credentials are provided.
- [IMPROVED] Preemptively renew authorization tokens that are due to expire.
> Prepare version 4.2.2 release.

- CHANGES.md
- README.md
Improve documentation around initialization callback.
Fixes #409
Make it clear in the documentation that using the intialization callback will always enable the `cookieauth` plugin.
Provide an example of using the `ping` function as an alternative to the initialization callback
- "No change"
- "No change"
- N/A doc only changes
- "No change"
> Improved docs for initialization callback

- CHANGES.md
- README.md
- lib/tokens/CookieTokenManager.js
- plugins/cookieauth.js
- test/plugins/cookieauth.js
Use `application/json` for `_session` POST of cookie auth
Pass a `url` containing percent-encoded user information.
cookieauth plugin session authentication to work correctly
`401 unauthorized` because the credentials were double encoded.
* Decoded credentials from URL before passing to `CookieTokenManager`.
* Prevents double encoding if passed in a form body
* Modified CookieTokenManager to use `json` body instead of `form` encoded anyway
* Improved documentation of characters that must be encoded.
- No change
Insignificant changes to handling of credentials
* For cookieauth credentials are now posted in a JSON body instead of as form encoded data, but it is the same request body as previously (i.e. if the server is https then the body containing the creds will be encrypted)
* …
> Used application/json for session POST

- CHANGES.md
- package-lock.json
- package.json
- [FIXED] Expose BasePlugin.
- [FIXED] Prevent double encoding of credentials passed in URL user information
when using the `cookieauth` plugin.
- [IMPROVED] Documented the characters that are required to be encoded in URL
user information.
- [IMPROVED] Documented the legacy compatibility behaviour that always adds the
`cookieauth` plugin when using the initialization callback functionality.
> Prepare 4.2.3 release

- CHANGES.md
- package-lock.json
- package.json
- [FIXED] Pinned Nano to version 8.1 to resolve issue with extending upstream
TypeScript changes in Nano version 8.2.0.
> Prepare 4.2.4 release

- test/client.js
- test/plugins/retry.js
Some of the tests assert on streaming response data in the `data` callback.  This can cause a failure since the assertion will fail in a case where there's more than one chunk of streaming data.  This PR concatenates the streaming data then asserts once the stream is completed in `end` block.
- Create a `responseString` variable to hold the streaming data and then assert on this variable once the stream is complete
- Removed failing and redundant data chunk count assertion.  We are already asserting on the streaming data
> Concatenate streaming data in client tests

- CHANGES.md
- lib/tokens/TokenManager.js
- test/tokens/TokenManager.js
The TokenManager supports auto renewal of tokens. It uses the Max-Age field of the cookie header or a default value to schedule a callback for the renewal.
Fixes #426
The problem is that the default value is only used for the first renewal. For subsequent renewals the default is undefined so the renewal is scheduled instantly unless a Max-Age field is found in the header:
```
_autoRenew(defaultMaxAgeSecs) {
debug('Auto renewing token now...');
this._renew().then((response) => {
let maxAgeSecs = cookie.parse(response.headers['set-cookie'][0])['Max-Age'] || defaultMaxAgeSecs;
let delayMSecs = maxAgeSecs / 2 * 1000;
debug(`Renewing token in ${delayMSecs} milliseconds.`);
setTimeout(this._autoRenew.bind(this), delayMSecs).unref(); <-- defaultMaxAgeSecs not passed on
}).catch((error) => { …
```
> Fix constant token renewal in the absence of a cookie Max-Age

- README.md
Update `README` to prefer `url` to `account` for init.
Fixes #435
Except for the explicit documentation about using the `account` option, replace other example init blocks to use `url`.
- "No change"
- "No change"
- N/A doc only changes
- "No change"
> Prefer url to account in README

- Jenkinsfile
- test/plugins/iamauth.js
Change the test server configuration and allow for overriding the token server used by tests.
Run Jenkins tests
Tests to pass
Tests failed because of a server config problem.
Replace the test server configuration in Jenkinsfile.
- "No change"
- "No change"
- Modified existing IAM auth plugin tests to use configured IAM token server when not nocked.
- "No change"
> Update test server config

- .mocharc.json
- .travis.yml
- CHANGES.md
- Jenkinsfile
- lib/clientutils.js
- lib/tokens/TokenManager.js
- package-lock.json
- package.json
- plugins/cookieauth.js
- plugins/iamauth.js
- test/mocha.opts
- test/plugins/iamauth.js
Correct opportunities for double callbacks
Fixes #454 
When writing tests I noticed that max-age was not correctly parsed from a single set cookie header (only from an array) - so there is one fix to resolve that issue.
Double callback (case 1):
In auth plugins for case where an error is encountered during state update.
The `cookieauth` and `iamauth` plugins are modified to `callback(state)` in a `finally` at the end of a promise chain instead of from two places in the `onRequest` function.
Double callback (case 2):
Discovered when updating nock to 13.x (see Test section below). In the case a request is aborted for a retry a double request `end` event might be received because (to [more precisely mirror current Node](https://github.com/nock/nock/blob/main/migration_guides/migrating_to_13.m …
> 454 double callback

- CHANGES.md
- package.json
Not yet complete. We need more changes first.
- [FIXED] Parsing of max-age from Set-Cookie headers.
- [FIXED] Double callback if plugin errors when updating state.
- [NOTE] Updated engines to remove EOL Node.js versions (minimum is now Node.js 12).
> Prepare 4.4.0 release

- CHANGES.md
- README.md
Add deprecation notice
Add notice to README, CHANGES.
Intent is to also issue `npm deprecate` command after this has merged to ensure deprecation warnings for library consumers.
Deprecation notice, library EOL.
- "No change"
- N/A documentation
- Warnings will be emitted on installation of the library after `npm deprecate`
> Add deprecation notice

- CHANGES.md
- README.md
- lib/clientutils.js
- plugins/retry.js
- test/plugins/retry.js
Ensure callback gets called for errors after response is already being processed.
Fixes #456 
* Add a flag when the execution loop is stopped.
* Force the client callback when processing a callback `error` if the flag is set.
* Update documentation to clarify behaviour of retry plugin.
It is worth noting the current behaviour on an error encountered during response processing when using the retry plugin is:
* The retry plugin asks for a retry, but it does not get executed.
* Callback style -> hangs with the callback not called
* Listener style -> an event is emitted for the error (between the `response` and `end` events)
This change retains the current behaviour except for the hang where the callback isn't called. It is not possible to allow retries once the response is already processing …
> 456 retry timeout hang

- CHANGES.md
- package-lock.json
- package.json
- [FIXED] Hang caused by plugins (i.e. retry plugin) preventing callback execution
by attempting to retry on errors received after starting to return the response body.
- [DEPRECATED] This library is now deprecated and will be EOL on Dec 31 2021.
> Prepare 4.4.1 release

- CHANGES.md
- lib/tokens/TokenManager.js
- test/plugins/cookieauth.js
Patch tough-cookie bug in TokenManager
Fixes #463
Patch the cookie jar used in the `TokenManager` with the workaround for sliding updates in `tough-cookie`. This is mostly the same patch we used in `cloudant-node-sdk` just with a slight change to the initial `_jar` checks to suit the `request` module.
- "No change"
- "No change"
- Added a new test to validate a renewed cookie is applied after the original session lifetime expired.
- "No change"
> Cookie persistence workaround

- CHANGES.md
- package-lock.json
- package.json
- [FIXED] Issue where new session cookies from pre-emptive renewal would not persist beyond the original session lifetime.
> Prepare 4.5.1 release

- MIGRATION.md
There have been some questions regarding migration lately. This PR tries to address them.
I clarified some of the questionable topics in this change:
* why is `use` not available anymore in the new SDK
* where users should check the server errors and the authentication errors
I also fixed a sentence where `are not transferable to` was there twice.
My IDE lately breaks the lines automatically, I have not figured out how I can turn it off yet, but I think this is a great feature, and it helps the reviewers to read the long lines more effectively, so I kept these modifications.
- "No change"
- "No change"
- N/A
- "No change"
> Improve migration guide
